Repository Leagify/prospect-scraper-dt2021, pull requests merged in 2020-10, with the labels that each got.

#23 Feature/dotnet 5 rc
  .gitpod.Dockerfile
  src/prospectScraper/prospectScraper.csproj
  test/prospectScraperTest/prospectScraperTest.csproj
Labels: hacktoberfest, hacktoberfest-approved

#26 Refactor Code Part 1
  src/prospectScraper/DTOs/SchoolMismatchDTO.cs
  src/prospectScraper/ExistingProspectRanking.cs
  src/prospectScraper/Maps/ExistingProspectRankingCsvMap.cs
  src/prospectScraper/Maps/MockDraftPickMap.cs
  src/prospectScraper/Maps/PointProjectionCsvMap.cs
  src/prospectScraper/Maps/PositionTypeCsvMap.cs
  src/prospectScraper/Maps/ProspectRankCsvMap.cs
  src/prospectScraper/Maps/ProspectRankingMap.cs
  src/prospectScraper/Maps/RegionCsvMap.cs
  src/prospectScraper/Maps/SchoolCsvMap.cs
  src/prospectScraper/MockDraftPick.cs
  src/prospectScraper/PointProjection.cs
  src/prospectScraper/PositionType.cs
  src/prospectScraper/Program.cs
  src/prospectScraper/ProspectRankSimple.cs
  src/prospectScraper/ProspectRanking.cs
  src/prospectScraper/ProspectRankingMap.cs
  src/prospectScraper/Region.cs
  src/prospectScraper/School.cs
  src/prospectScraper/prospectScraper.csproj
  src/prospectScraper/prospectScraper.sln
  test/prospectScraperTest/UnitTest1.cs
  test/prospectScraperTest/prospectScraperTest.csproj
Labels: hacktoberfest, hacktoberfest-approved

#21 #20 Add unit tests to cover a random collection of functionality.
  src/prospectScraper/Program.cs
  test/prospectScraperTest/ProgramTest.cs
Labels: hacktoberfest, hacktoberfest-approved, tests

#24 added few unit tests
  test/prospectScraperTest/MockDraftPickTests.cs
  test/prospectScraperTest/ProgramTest.cs
  test/prospectScraperTest/UnitTest1.cs
Labels: hacktoberfest, hacktoberfest-approved, tests

#35 fixes csproj/sln and adds parameter - Closes #32
  README.md
  src/prospectScraper/Program.cs
  src/prospectScraper/ProspectScraper.csproj
  src/prospectScraper/ProspectScraper.sln
  src/prospectScraper/logs/Prospects.log
  src/prospectScraper/logs/Status.log
  src/prospectScraper/mocks/2020-10-07-mock.csv
  src/prospectScraper/ranks/2020-10-09-ranks.csv
  src/prospectScraper/ranks/combinedRanks2021.csv
  src/prospectScraper/ranks/joinedRanks2021.csv
  test/prospectScraperTest/ProspectScraperTest.csproj
Labels: hacktoberfest, hacktoberfest-approved

#36 Adding build step to build solution and run unit test
  .github/workflows/build.yml
  test/prospectScraperTest/MockDraftPickTests.cs
  test/prospectScraperTest/ProgramTest.cs
Labels: hacktoberfest, hacktoberfest-approved

#29 Refactor Code Part 2
  src/prospectScraper/ExistingProspectRanking.cs
  src/prospectScraper/Maps/ExistingProspectRankingCsvMap.cs
  src/prospectScraper/Maps/PointProjectionCsvMap.cs
  src/prospectScraper/Maps/PositionTypeCsvMap.cs
  src/prospectScraper/MockDraftPick.cs
  src/prospectScraper/Player.cs
  src/prospectScraper/PointProjection.cs
  src/prospectScraper/PositionType.cs
  src/prospectScraper/Program.cs
  src/prospectScraper/ProspectScraper.cs
  src/prospectScraper/School.cs
  test/prospectScraperTest/MockDraftPickTests.cs
  test/prospectScraperTest/ProgramTest.cs
Labels: hacktoberfest

#37 2020ScheduledGames.csv added
  src/prospectScraper/info/2020ScheduledFallGames.csv
Labels: hacktoberfest, hacktoberfest-approved

#28 new test
  test/prospectScraperTest/MockDraftPickTests.cs
Labels: hacktoberfest

#39 adds new board and mock, updates school filtering
  src/prospectScraper/School.cs
  src/prospectScraper/logs/Mismatches.log
  src/prospectScraper/logs/Prospects.log
  src/prospectScraper/logs/Status.log
  src/prospectScraper/mocks/2020-10-21-mock.csv
  src/prospectScraper/ranks/2020-10-13-ranks.csv
  src/prospectScraper/ranks/combinedRanks2021.csv
  src/prospectScraper/ranks/joinedRanks2021.csv
Labels: big-board, hacktoberfest, mock-draft
